### ISSUE TITLE
[LICENSE] LuckPerms 

### ISSUE THREAD

**Issue by Romvnly-Gaming** [sVoxelDev/multi-platform-plugin-template#11]
A lot of this plugin's code/structure comes from LuckPerms. Maybe you should add them to the license or whatever.

You need to credit them according to their license on their code. 
![image](https://user-images.githubusercontent.com/62443489/152183914-43abff75-60aa-4882-b737-8d7fc5ab69bc.png)

**Comment by Silthus** [comment]
Luckperms is mentioned in the Readme and the license notice refers to the MIT license.

Also this isn't ready for public use yet and a lot of things need to be cleaned up before it can be used.

PRs are welcome if you want to contribute ;)

**Comment by Romvnly-Gaming** [comment]
I'm still gonna use it >:(

**Comment by Silthus** [comment]
You can run the update licenses task in the root project to fix all of the license headers.
